### ISSUE TITLE
Hybrid Remote App - redirects back to login screen after doing "Forget Passcode/Pin" flow

### ISSUE THREAD

**Issue by GaneshSawant** [forcedotcom/SalesforceMobileSDK-Android#1345]
Please fill out the following details:

1. Version of Mobile SDK Used: 5.0.0 and 4.3.0
2. Issue found in Native App or Hybrid App: Hybrid App
3. OS Version: Marshmallow 
4. Device: One Plus 3
5. Steps to reproduce:
     Activate the Pin Protection on the Connected App. On first Install of App, set the Passcode
     After timeout mentioned in the Connected App, system asks for Pin as additional security Layer.
     Lets say, user forgot the Pin, when we click the "forget Passcode" link from the Pin Screen, an User forced to logout of the app and asked to enter Username and Password again.
After entering Username and Password, User redirected to new Pin Setup Screens.
On setting up new Pin, the flow takes back to the login screen again instead of App's Landing Page.
In the backend the login is actually successful and the new pin is already set up but somehow the Internal Authorization page giving some error.

Uncaught TypeError: Cannot set property 'value' of null
    at window.onload (RemoteAccessAuthorizationPage.apexp:442)

**Comment by GaneshSawant** [comment]
Hello Team, 

May I please know if any updates on this Particular Issue.

Thank you,
Ganesh

**Comment by huminzhi** [comment]
Hi, @GaneshSawant We are able to reproduce the issue and a fix is undergoing. Thank you very much!

**Comment by GaneshSawant** [comment]
hello @huminzhi , 

Many thanks for looking into this Issue. 
May I know if we have to wait for the fix till next available release as we are planning to go live in less than a months time.

Can we do it a quick fix may be fixing a specific SDK java class or a cordova Javascript library ?

Regards,
Ganesh

**Comment by huminzhi** [comment]
https://github.com/forcedotcom/SalesforceMobileSDK-Android/blob/dev/libs/SalesforceSDK/src/com/salesforce/androidsdk/ui/LoginActivity.java#L315. It is resolved in latest dev branch @GaneshSawant

**Comment by huminzhi** [comment]
@GaneshSawant  to use latest dev branch code

1) Clone the Mobile SDK cordova plugin repo and checkout the dev branch
git clone https://github.com/forcedotcom/SalesforceMobileSDK-CordovaPlugin
cd SalesforceMobileSDK-CordovaPlugin
git checkout dev

2) modify ./tools/update.sh if you need to change the repo path to your fork: (you can skip this step)

3) Build the libraries (we only checkin the libraries when we have a release)
./tools/update.sh -b dev

4) In your application, remove the Mobile SDK plugin and add it back by pointing to your local clone
cd app-folder
cordova plugin remove com.salesforce
cordova plugin add plugin-clone-parent-folder/SalesforceMobileSDK-CordovaPlugin

**Comment by huminzhi** [comment]
The issue is fixed on the 'dev' branch.
Please try to reproduce again and see if it still exists. Thank you!

**Comment by GaneshSawant** [comment]
Hello Team, 

I cant use the dev repo as the cordova and forcedroid versions are 5.4.0 and 4.3.0 respectively which is giving us an error.
We didnt upgraded to latest salesforce sdk 5.0.0 because of following issue
https://github.com/forcedotcom/SalesforceMobileSDK-Android/issues/1341

Can you please look into 1341 please

**Comment by Manjeetmetacube** [comment]
Hi,
I am facing the similar issue by below steps:
login with USER 1
After PIN timeout occurs and we do the forgot pin passcode
Login screen comes again
login with USER 2
when you come back to the main application UI thread it still shows the USER 1.

Can anybody help on this?

**Comment by Manjeetmetacube** [comment]
One more question on some of the android device if we login in the android hybrid app which is based on salesforce mobile sdk. we run the app then see the recent apps then it shows two app one for application and one for hybrid app.  Why so?

**Comment by brandonpage** [comment]
Hi @Manjeetmetacube, I discovered and fixed many issues related to this in the last few weeks.  I am unable to reproduce this issue locally so it should be fixed in the next release. 

I have not seen an hybrid app show up multiple times in the app drawer.  If you are using the latest version of Mobile SDK and believe it is an issue we caused please file a separate issue.

**Comment by Manjeetmetacube** [comment]
Ok Great. Thanks for the update.I can not do the upgrade right now. Can you help me in fixing this locally?

**Comment by Manjeetmetacube** [comment]
I guess application should get logged out from the logged in user if the forgot passcode is opted which is not working right now.
