### ISSUE TITLE
Facing Background crash

### ISSUE THREAD

**Issue by HardiDarshankumarBavariya** [forcedotcom/SalesforceMobileSDK-Android#2705]
-  I’m sharing the details regarding the recent crash issues we encountered after upgrading the Salesforce SDK.
- We recently upgraded the Salesforce SDK from v12.1.1 to v12.2.0, and since the upgrade, we’ve observed crashes in the application. Please find the relevant details below along with the attached crash logs for further analysis.

**Current Configuration:**
Salesforce SDK Version: 12.2.0
React Native Version: 0.74.0
minSdkVersion: 26
targetSdkVersion: 34
compileSdkVersion: 34

[ReactBridge.txt](https://github.com/user-attachments/files/19832208/ReactBridge.txt)
[SmartStoreReactBridge.txt](https://github.com/user-attachments/files/19832209/SmartStoreReactBridge.txt)

**Comment by johnjeremih** [comment]
For your records, the error is located in int com.facebook.react.bridge.ReadableArray.size(), and the second one is on SmartStore.getDatabase().  Are you using dependencies, or do you have the module on the app? Are you using a native app or a hybrid?

**Comment by wmathurin** [comment]
Could you try using the latest Mobile SDK version (13.0.2)? We only release fixes in new versions, so your issue may already be resolved in this update.

**Comment by wmathurin** [comment]
Could you try using the latest Mobile SDK version (13.1.0) which was released Monday 9/29 ?
It uses React Native 0.79.3.

**Comment by HardiDarshankumarBavariya** [comment]
ok @wmathurin I will try with latest Mobile SDK version 13.1.0, Thank you for your support.

**Comment by vikasshahtcpl** [comment]
I am also facing same issue in 12.2.0,13.1.0,13.2.0
but still not solved

**SmartStoreReactBridge.upsertSoupEntries**

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'net.zetetic.database.sqlcipher.SQLiteDatabase com.salesforce.androidsdk.smartstore.store.SmartStore.getDatabase()' on a null object reference
       at com.salesforce.androidsdk.reactnative.bridge.SmartStoreReactBridge.upsertSoupEntries(SmartStoreReactBridge.java:282)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.kt:217)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.kt:134)
       at com.facebook.jni.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.kt:21)
       at android.os.Looper.loopOnce(Looper.java:222)
       at android.os.Looper.loop(Looper.java:314)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion.startNewBackgroundThread$lambda$1(MessageQueueThreadImpl.kt:175)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion.$r8$lambda$ldnZnqelhYFctGaUKkOKYj5rxo4()
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$Companion$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at java.lang.Thread.run(Thread.java:1564)

**Comment by wmathurin** [comment]
In SDK 14.0, all React Native bridge code (including `SmartStoreReactBridge`) has moved from this repo to [`forcedotcom/SalesforceMobileSDK-ReactNative`](https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative). The background crash you described is a React Native-specific issue and should be tracked there. Please re-open at https://github.com/forcedotcom/SalesforceMobileSDK-ReactNative/issues/new with your stack trace and SDK version — the correct team will see it. Closing here.
